### ISSUE TITLE
Demo project in Readme don't work in MacOS 13

### ISSUE THREAD

**Issue by AndyJado** [MoonZoon/MoonZoon#114]
```
  Finished dev [unoptimized + debuginfo] target(s) in 19.45s
Downloading & Installing wasm-bindgen 0.2.81 ...
Pre-compiled wasm-bindgen binary 'x86_64-apple-darwin' will be used for the target platform 'aarch64-apple-darwin'

```

**Comment by AndyJado** [comment]
Oh it worked after a while! what a beautiful counter!

**Comment by MartinKavik** [comment]
Feel free to create a PR with updated texts to make them less confusing if you want :)

**Comment by AndyJado** [comment]
is it possible I update was-bindgen to a newer version?

[this seem to fix the problem](https://github.com/rustwasm/wasm-pack/releases/tag/v0.10.2)

> Pre-compiled wasm-bindgen binary 'x86_64-apple-darwin' will be used for the target platform 'aarch64-apple-darwin'

can be a real pain, it took 10min for each example before able to run.

**Comment by AndyJado** [comment]
Well Finally.

## TL,DR: x86 won't slow down you m1 MacBook noticeably.

it was the Internet wall my country built.😮‍💨

1. I went to mzoon/src/wasm_bindgen.rs
2. I changed 0.2.81 to some 9.9.9
3. it leads me to https://github.com/rustwasm/wasm-bindgen/releases

- I suddenly realize I used proxy for Cargo but this is unexpected download
- I turn on global proxy and it flows like a river

**Comment by MartinKavik** [comment]
> it was the Internet wall my country built.

I thought so, `mzoon` just downloads the `wasm-bindgen` from the [GitHub releases](https://github.com/rustwasm/wasm-bindgen/releases). The code/url below. 

https://github.com/MoonZoon/MoonZoon/blob/e4d55d7f3aa276922786be8b7a18a05b01ba6b66/crates/mzoon/src/wasm_bindgen.rs#L38

I adapt MoonZoon to the latest `wasm-bindgen`, `wasm-opt` and Rust version manually once new versions appear. 
I'll also add native `wasm-bindgen` M1 support once it's possible (you can let me know when you notice there is a new macos binary in the `wasm-bindgen` repo).

**Comment by AndyJado** [comment]
Hello again!
## Error be like:

`Error: Failed to optimize frontend with wasm-opt`

## What I did:

```
cd example/pages

mzoon build --release --frontend-dist
```

## what it said:

> wasm-opt installed
dyld[11872]: Library not loaded: @rpath/libbinaryen.dylib
  Referenced from: <6DD30678-B5A9-3D4E-8E69-B9DC6B8B9C27> /Users/andyjado/Projects/MoonZoon/examples/pages/frontend/wasm-opt
  Reason: tried: '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/usr/local/lib/libbinaryen.dylib' (no such file), '/usr/lib/libbinaryen.dylib' (no such file, not in dyld cache)
Error: Failed to optimize frontend with wasm-opt
