### ISSUE TITLE
wasm-opt + MacOS 13 M1 problem

### ISSUE THREAD

**Issue by MartinKavik** [MoonZoon/MoonZoon#116]
Hello again!
## Error be like:

`Error: Failed to optimize frontend with wasm-opt`

## What I did:

```
cd example/pages

mzoon build --release --frontend-dist
```

## what it said:

> wasm-opt installed
dyld[11872]: Library not loaded: @rpath/libbinaryen.dylib
  Referenced from: <6DD30678-B5A9-3D4E-8E69-B9DC6B8B9C27> /Users/andyjado/Projects/MoonZoon/examples/pages/frontend/wasm-opt
  Reason: tried: '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/Users/andyjado/Projects/MoonZoon/examples/pages/frontend/../lib/libbinaryen.dylib' (no such file), '/usr/local/lib/libbinaryen.dylib' (no such file), '/usr/lib/libbinaryen.dylib' (no such file, not in dyld cache)
Error: Failed to optimize frontend with wasm-opt

_Originally posted by @AndyJado in https://github.com/MoonZoon/MoonZoon/issues/114#issuecomment-1179517932_

**Comment by MartinKavik** [comment]
The `wasm-opt` is downloaded here:
https://github.com/MoonZoon/MoonZoon/blob/e4d55d7f3aa276922786be8b7a18a05b01ba6b66/crates/mzoon/src/wasm_opt.rs#L24-L39

And used here:
https://github.com/MoonZoon/MoonZoon/blob/e4d55d7f3aa276922786be8b7a18a05b01ba6b66/crates/mzoon/src/wasm_opt.rs#L56-L79

You can try to download it manually from https://github.com/WebAssembly/binaryen/releases and extract `wasm-opt` binary to your project's `frontend` folder to test it manually. I'm not sure if it's Binaryen or MoonZoon problem.

Unfortunately I don't have Mac and most problems are with Mac and Safari/iOS so I would be glad for help.

**Comment by AndyJado** [comment]
`wasm-opt` wasn't the problem as is shown in the message but

### `lib/libbinaryen.dylib`

I paste it into my project's frontend folder but the same error appears.

---

 however I double click this `dylib` , it returns:

> zsh: exec format error: /Users/andyjado/Downloads/binaryen-version_109/lib/libbinaryen.dylib

**Comment by AndyJado** [comment]
does it help if I use docker?

**Comment by Firfi** [comment]
same issue on m1

**Comment by MartinKavik** [comment]
Fixed in #171

**Comment by Firfi** [comment]
Still seems to be the issue on my side, despite getting the latest version from git

```
[workspace.dependencies]
moon = { git = "https://github.com/MoonZoon/MoonZoon", rev = "ccc15d043e78a6656d68a60d46de1f540724e093" }
zoon = { git = "https://github.com/MoonZoon/MoonZoon", ref = "ccc15d043e78a6656d68a60d46de1f540724e093" }
```

<img width="1187" alt="Screenshot 2023-04-30 at 4 15 58 PM" src="https://user-images.githubusercontent.com/947595/235345560-dad01169-146f-4386-8972-c2a1191a3cd7.png">

reproducible example https://github.com/Firfi/shades-of-rust/tree/master/shades-moonzoon

**Comment by MartinKavik** [comment]
@Firfi All changes related to the fix has been done in the `mzoon` crate - have you updated it as well?

**Comment by Firfi** [comment]
@MartinKavik my bad, I didn't update the CLI itself 😅 It doesn't fail the build anymore. Thank you!
