### ISSUE TITLE
Logo Idea(s)

### ISSUE THREAD

**Issue by DvirArazi** [MoonZoon/MoonZoon#129]
First I want to point out that the opinions presented here are completely subjective, though I do feel most people in the community  will tend to agree with me.

I feel that the MoonZoon logo is in need for rebranding.
I believe that the current logo is overly detailed and filled with unnecessary elements such as the three lines crossing the the 'Z', the black background with chamfered edges, and the lighting in the edges of the shapes.
It looks cluttered and not very professional. Hardly a good fit for a high quality production framework.

My suggestion for the new logo aims to be modern and clean while highlighting it's connection to the Rust programming language and keeping with the theme of the current logo.
The connection to Rust is represented by the motif of the sprocket enveloping a single character.
The use of the Alfa Slab One font invokes a feeling of presence and solidity (in addition to farther emphasizing the connection with Rust, since it is featured in several places on the Rust language website).
The sprocket is made in the shape of a crescent moon to keep in line with the current logo's signature latter 'Z' enveloped in a crescent moon.

Icon only:
Light Mode | Dark Mode
:-:|:-:
![moonzoon_logo](https://user-images.githubusercontent.com/108592948/183472321-9ef8e80d-6487-4852-aab0-fd453f7ff537.svg) | ![moonzoon_logo_dark](https://user-images.githubusercontent.com/108592948/183473508-9ba38eac-b109-4c26-9839-03d4bf1bb774.svg)

Icon + Name:
Light Mode | Dark Mode
:-:|:-:
![moonzoon_logo_name](https://user-images.githubusercontent.com/108592948/183472500-70de8822-6427-4746-aa85-43859dccf1bf.svg) | ![moonzoon_logo_name_dark](https://user-images.githubusercontent.com/108592948/183473619-858aa27d-b74e-4e94-9773-15d799f56b3e.svg)

For socials:
Light Mode | Dark Mode
:-:|:-:
![moonzoon_logo_social](https://user-images.githubusercontent.com/108592948/183472539-d65664bd-fb8f-4b18-916d-bbdd046f4ff6.svg) | ![moonzoon_logo_social_dark](https://user-images.githubusercontent.com/108592948/183473653-853647ee-aca3-4530-a3ba-134e3eb3732a.svg)

**Comment by MartinKavik** [comment]
Could you post the logo version for dark background, too? I want to know your color preference (grey, white, ..) and the logos posted above are almost invisible for people who use dark GitHub mode. Thanks!

What editor have you used to create them?

**Comment by DvirArazi** [comment]
Sure, I'll make the other version now. In general I think simple black on white looks the best, but it usually depends on where the logo is presented. I used [Boxy SVG Editor](https://boxy-svg.com/).

**Comment by databasedav** [comment]
@MartinKavik are u concerned at all about the "Z" being the centerpiece of the logo? it feels to me to imply that Zoon is the focus of the framework and the backend Moon is kind of a lesser appendage to the "central" frontend part

note, i'm a fan of the new logo and this vibe of frontend/backend imbalance of course doesn't mean MoonZoon actually puts Zoon before Moon, just wanted to share my non-designer thoughts :)

**Comment by MartinKavik** [comment]
> are u concerned at all about the "Z" being the centerpiece of the logo?

Well, Zoon is currently more developed than Moon so from this (temporary) point of view it makes sense.
I perceive the letter Z as a smaller symbol in front of the Moon where you see only a part of the Moon (the crescent). This way it's balanced.
Honestly, I was afraid it would look like sprayed Z on a rust gear... from a tank or something like that... Having Z symbol is a bit unfortunate during the war.

But I think the logo is nice and I hope I won't need to change it in the foreseeable future.

**Comment by MartinKavik** [comment]
Logo updated in README, GitHub project settings and Discord; variants saved to the [branding](https://github.com/MoonZoon/MoonZoon/tree/main/branding) folder.

I was fighting a bit with format because Affinity Designer apparently can't handle some types of viewport settings and masks in provided SVGs but it should be good enough I hope. (Neither Boxy SVG Editor can't work with the masks even in the SVGs that it created.) The only solution seems to be to don't use masks in Boxy at all and export SVG with non-default viewport settings I think.

@DvirArazi Thank you very much!
