### ISSUE TITLE
ensure it's installable for termux

### ISSUE THREAD

**Issue by ghost** [MoonZoon/MoonZoon#141]
Termux is a terminal emulator for Android. Some packages are not found in termux, but can be installed on Arch, Debian, Ubuntu and common distros. It's also difficult or impossible to install Moonzoon in Termux, since rustup is missing in Termux repo. By the way, could you please upload Moonzoon to [Crates.io](https://crates.io) ?

**Comment by MartinKavik** [comment]
> It's also difficult or impossible to install Moonzoon in Termux, since rustup is missing in Termux repo.

I don't think `rustup` is used in the MZ codebase. Does a dependency require it? Or what is the problem?

> By the way, could you please upload Moonzoon to [Crates.io](https://crates.io/) ?

It isn't on my short-term roadmap. Why do you need it?

Also I'm curious - why do you want to install MZ in Termux?

**Comment by dotridat** [comment]
> Also I'm curious - why do you want to install MZ in Termux?

Currently, I don't have enough money to buy a computer.
