### ISSUE TITLE
Q: Is there a way to insert a link mid paragraph?

### ISSUE THREAD

**Issue by ruza-net** [MoonZoon/MoonZoon#151]
Is there a way to for example make one word of a paragraph a link, preferably without injecting HTML in a string?

Update: More generally, can a single word of paragraph be styled separately (made bold, etc.)?

**Comment by MartinKavik** [comment]
Sure, see the `paragraph` example in the repo:
https://github.com/MoonZoon/MoonZoon/blob/6b7b3f12cb2ef6fd4f067ea7079c2be8992394ae/examples/paragraph/frontend/src/main.rs#L35-L53
![image](https://user-images.githubusercontent.com/18517402/202874996-e8375390-42e6-4346-bbbc-e7cabab976f2.png)
