### ISSUE TITLE
allow constructing `Oscillator` with a `impl Fn() -> Duration`

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#153]
this would enable lazily computed transition durations per oscillation, e.g. if we wanted each oscillation interval to be random

**Comment by MartinKavik** [comment]
Could you provide an example please? I'm not sure I really understand it / don't see the motivation and I would like to think about possible alternatives.
Thanks!  And sorry for the late response.

**Comment by databasedav** [comment]
so an example would be any situation where we don't want the oscillation interval to be static, like imagine a loading icon that moves up and down (or in some other way, in a circular, quadrilateral, etc. motion) per oscillation, and we want this interval to decrease per oscillation, completing the entire movement interval faster

**Comment by MartinKavik** [comment]
I've just merged a PR https://github.com/MoonZoon/MoonZoon/pull/158 with new example `spinner` and new method `Oscillator::set_duration`. The example demonstrates how to write a loading spinner with a smoothly changing speed.
Do you think the new method will be enough for your use-case?

**Comment by databasedav** [comment]
@MartinKavik yes that's perfect, thanks :pray:
