### ISSUE TITLE
:pray: Q&A: MoonZoon Why convert to WebAssembly?

### ISSUE THREAD

**Issue by jujubeja** [MoonZoon/MoonZoon#208]
MoonZoon needs a rust browser?

https://github.com/servo/servo Servo, the embeddable, independent, memory-safe, modular, parallel web rendering engine

https://github.com/LadybirdBrowser/ladybird is a truly independent web browser, using a novel engine based on web standards.

https://github.com/AgregoreWeb/agregore-browser A minimal web browser for the distributed web

**Comment by MartinKavik** [comment]
Only for prerendering to improve SEO or as a part of Tauri to write desktop apps in MoonZoon. I follow the Servo progress.
