### ISSUE TITLE
UpHandler trait is too restrictive

### ISSUE THREAD

**Issue by allsey87** [MoonZoon/MoonZoon#22]
The UpHandler trait is currently defined as:
```rust
pub trait UpHandler<UPHO: UpHandlerOutput, UMsg> = Fn(UpMsgRequest<UMsg>) -> UPHO + Clone + Send + 'static;
```
`Fn` trait (in comparison to `FnOnce`) is quite restrictive and makes it very difficult to interact with parts of the program that are not global or were not instantiated inside the provided `UpHandler`. For example, consider a case where it is desirable to forward `UpMsg`s using a MPSC channel:
```rust
async fn launch(tx: mpsc::Sender<UpMsg>) -> std::io::Result<()> {
    let frontend = || async {
        Frontend::new()
    };
    let handler = |req: UpMsgRequest<UpMsg>| async {
        let UpMsgRequest { up_msg, .. } = req;
        tx.send(up_msg).await;
    };
    moon::start(frontend, handler, |_| {}).await
}
```
This code doesn't compile since `handler` may outlive `tx`, which `handler` has a reference to. Changing this code so that `tx` is moved inside the closure, however, changes the closure to `FnOnce` which `moon::start` doesn't accept.

**Comment by MartinKavik** [comment]
It's resolved in this commit: https://github.com/MartinKavik/MoonZoon/commit/50b8d0857ef501ca085221f0798ee8b253a32f9c
I'll merge it together with routing (during the following days with a bit of luck)

**Comment by MartinKavik** [comment]
PR https://github.com/MoonZoon/MoonZoon/pull/25 with the fix merged, closing.
