### ISSUE TITLE
allow `Placeholder` to take arbitrary `impl Element`'s

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#45]
if possible, it would be great to be able to place things like images, buttons, and formatted text, etc. in a `TextInput`'s placeholder

**Comment by MartinKavik** [comment]
Only text with a limited set of styles is allowed to use as a placeholder by browsers. I don't think we can create a custom `TextInput` that isn't based on a standard HTML `input` without breaking UX / accessibility and extensions like password managers.
I don't have a problem with revisiting the issue when there is a support in browsers.

I've added the method `Placeholder::with_signal`. We can add something like `PlaceholderStyle` later when it makes sense to ensure the user uses only styles applicable to a placeholder. However, it should be good enough for now - closing.
