### ISSUE TITLE
add signal methods for `on_click` family

### ISSUE THREAD

**Issue by databasedav** [MoonZoon/MoonZoon#74]
right now, you must wrap the entire element in a signal for the on click handler to be dynamic

**Comment by MartinKavik** [comment]
What's your use case? There are many things to consider before adding "signaled" handlers.

I don't need to "toggle" handlers too often in my code and when I need to do it, it looks like:
```rust
.on_click(move || {
    if mutable_is_button_disabled.get() {
        return;
    }
    do_something();
})
```

**Comment by databasedav** [comment]
@MartinKavik ya doing it like that actually suffices for my use case, however this would still be useful once we reach the level of abstraction where we want to pass functions to element factories that are decoupled from their local mutable state

i haven't reach this level yet so i'll reopen when i do :)
